// File generated from our OpenAPI spec by Stainless.

package io.imagekit.io.models.accounts.origins

import io.imagekit.io.core.Params
import io.imagekit.io.core.checkRequired
import io.imagekit.io.core.http.Headers
import io.imagekit.io.core.http.QueryParams
import java.util.Objects
import java.util.Optional
import kotlin.jvm.optionals.getOrNull

/**
 * **Note:** This API is currently in beta. Updates the origin identified by `id` and returns the
 * updated origin object.
 */
class OriginUpdateParams
private constructor(
    private val id: String?,
    private val originRequest: OriginRequest,
    private val additionalHeaders: Headers,
    private val additionalQueryParams: QueryParams,
) : Params {

    /**
     * Unique identifier for the origin. This is generated by ImageKit when you create a new origin.
     */
    fun id(): Optional<String> = Optional.ofNullable(id)

    /** Schema for origin request resources. */
    fun originRequest(): OriginRequest = originRequest

    /** Additional headers to send with the request. */
    fun _additionalHeaders(): Headers = additionalHeaders

    /** Additional query param to send with the request. */
    fun _additionalQueryParams(): QueryParams = additionalQueryParams

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [OriginUpdateParams].
         *
         * The following fields are required:
         * ```java
         * .originRequest()
         * ```
         */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [OriginUpdateParams]. */
    class Builder internal constructor() {

        private var id: String? = null
        private var originRequest: OriginRequest? = null
        private var additionalHeaders: Headers.Builder = Headers.builder()
        private var additionalQueryParams: QueryParams.Builder = QueryParams.builder()

        @JvmSynthetic
        internal fun from(originUpdateParams: OriginUpdateParams) = apply {
            id = originUpdateParams.id
            originRequest = originUpdateParams.originRequest
            additionalHeaders = originUpdateParams.additionalHeaders.toBuilder()
            additionalQueryParams = originUpdateParams.additionalQueryParams.toBuilder()
        }

        /**
         * Unique identifier for the origin. This is generated by ImageKit when you create a new
         * origin.
         */
        fun id(id: String?) = apply { this.id = id }

        /** Alias for calling [Builder.id] with `id.orElse(null)`. */
        fun id(id: Optional<String>) = id(id.getOrNull())

        /** Schema for origin request resources. */
        fun originRequest(originRequest: OriginRequest) = apply {
            this.originRequest = originRequest
        }

        /** Alias for calling [originRequest] with `OriginRequest.ofS3(s3)`. */
        fun originRequest(s3: OriginRequest.S3) = originRequest(OriginRequest.ofS3(s3))

        /** Alias for calling [originRequest] with `OriginRequest.ofS3Compatible(s3Compatible)`. */
        fun originRequest(s3Compatible: OriginRequest.S3Compatible) =
            originRequest(OriginRequest.ofS3Compatible(s3Compatible))

        /**
         * Alias for calling [originRequest] with
         * `OriginRequest.ofCloudinaryBackup(cloudinaryBackup)`.
         */
        fun originRequest(cloudinaryBackup: OriginRequest.CloudinaryBackup) =
            originRequest(OriginRequest.ofCloudinaryBackup(cloudinaryBackup))

        /** Alias for calling [originRequest] with `OriginRequest.ofWebFolder(webFolder)`. */
        fun originRequest(webFolder: OriginRequest.WebFolder) =
            originRequest(OriginRequest.ofWebFolder(webFolder))

        /** Alias for calling [originRequest] with `OriginRequest.ofWebProxy(webProxy)`. */
        fun originRequest(webProxy: OriginRequest.WebProxy) =
            originRequest(OriginRequest.ofWebProxy(webProxy))

        /**
         * Alias for calling [originRequest] with the following:
         * ```java
         * OriginRequest.WebProxy.builder()
         *     .name(name)
         *     .build()
         * ```
         */
        fun webProxyOriginRequest(name: String) =
            originRequest(OriginRequest.WebProxy.builder().name(name).build())

        /** Alias for calling [originRequest] with `OriginRequest.ofGcs(gcs)`. */
        fun originRequest(gcs: OriginRequest.Gcs) = originRequest(OriginRequest.ofGcs(gcs))

        /** Alias for calling [originRequest] with `OriginRequest.ofAzureBlob(azureBlob)`. */
        fun originRequest(azureBlob: OriginRequest.AzureBlob) =
            originRequest(OriginRequest.ofAzureBlob(azureBlob))

        /** Alias for calling [originRequest] with `OriginRequest.ofAkeneoPim(akeneoPim)`. */
        fun originRequest(akeneoPim: OriginRequest.AkeneoPim) =
            originRequest(OriginRequest.ofAkeneoPim(akeneoPim))

        fun additionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun additionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun putAdditionalHeader(name: String, value: String) = apply {
            additionalHeaders.put(name, value)
        }

        fun putAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.put(name, values)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun replaceAdditionalHeaders(name: String, value: String) = apply {
            additionalHeaders.replace(name, value)
        }

        fun replaceAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.replace(name, values)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun removeAdditionalHeaders(name: String) = apply { additionalHeaders.remove(name) }

        fun removeAllAdditionalHeaders(names: Set<String>) = apply {
            additionalHeaders.removeAll(names)
        }

        fun additionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun additionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun putAdditionalQueryParam(key: String, value: String) = apply {
            additionalQueryParams.put(key, value)
        }

        fun putAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.put(key, values)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.putAll(additionalQueryParams)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.putAll(additionalQueryParams)
            }

        fun replaceAdditionalQueryParams(key: String, value: String) = apply {
            additionalQueryParams.replace(key, value)
        }

        fun replaceAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.replace(key, values)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.replaceAll(additionalQueryParams)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.replaceAll(additionalQueryParams)
            }

        fun removeAdditionalQueryParams(key: String) = apply { additionalQueryParams.remove(key) }

        fun removeAllAdditionalQueryParams(keys: Set<String>) = apply {
            additionalQueryParams.removeAll(keys)
        }

        /**
         * Returns an immutable instance of [OriginUpdateParams].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```java
         * .originRequest()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): OriginUpdateParams =
            OriginUpdateParams(
                id,
                checkRequired("originRequest", originRequest),
                additionalHeaders.build(),
                additionalQueryParams.build(),
            )
    }

    fun _body(): OriginRequest = originRequest

    fun _pathParam(index: Int): String =
        when (index) {
            0 -> id ?: ""
            else -> ""
        }

    override fun _headers(): Headers = additionalHeaders

    override fun _queryParams(): QueryParams = additionalQueryParams

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is OriginUpdateParams &&
            id == other.id &&
            originRequest == other.originRequest &&
            additionalHeaders == other.additionalHeaders &&
            additionalQueryParams == other.additionalQueryParams
    }

    override fun hashCode(): Int =
        Objects.hash(id, originRequest, additionalHeaders, additionalQueryParams)

    override fun toString() =
        "OriginUpdateParams{id=$id, originRequest=$originRequest, additionalHeaders=$additionalHeaders, additionalQueryParams=$additionalQueryParams}"
}
