// File generated from our OpenAPI spec by Stainless.

package com.imagekit.api.services.blocking.accounts

import com.google.errorprone.annotations.MustBeClosed
import com.imagekit.api.core.ClientOptions
import com.imagekit.api.core.RequestOptions
import com.imagekit.api.core.http.HttpResponse
import com.imagekit.api.core.http.HttpResponseFor
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointCreateParams
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointCreateResponse
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointDeleteParams
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointGetParams
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointGetResponse
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointListParams
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointListResponse
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointUpdateParams
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointUpdateResponse
import java.util.function.Consumer

interface UrlEndpointService {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): UrlEndpointService

    /**
     * **Note:** This API is currently in beta. Creates a new URL‑endpoint and returns the resulting
     * object.
     */
    fun create(params: UrlEndpointCreateParams): UrlEndpointCreateResponse =
        create(params, RequestOptions.none())

    /** @see create */
    fun create(
        params: UrlEndpointCreateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointCreateResponse

    /**
     * **Note:** This API is currently in beta. Updates the URL‑endpoint identified by `id` and
     * returns the updated object.
     */
    fun update(id: String, params: UrlEndpointUpdateParams): UrlEndpointUpdateResponse =
        update(id, params, RequestOptions.none())

    /** @see update */
    fun update(
        id: String,
        params: UrlEndpointUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointUpdateResponse = update(params.toBuilder().id(id).build(), requestOptions)

    /** @see update */
    fun update(params: UrlEndpointUpdateParams): UrlEndpointUpdateResponse =
        update(params, RequestOptions.none())

    /** @see update */
    fun update(
        params: UrlEndpointUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointUpdateResponse

    /**
     * **Note:** This API is currently in beta. Returns an array of all URL‑endpoints configured
     * including the default URL-endpoint generated by ImageKit during account creation.
     */
    fun list(): List<UrlEndpointListResponse> = list(UrlEndpointListParams.none())

    /** @see list */
    fun list(
        params: UrlEndpointListParams = UrlEndpointListParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): List<UrlEndpointListResponse>

    /** @see list */
    fun list(
        params: UrlEndpointListParams = UrlEndpointListParams.none()
    ): List<UrlEndpointListResponse> = list(params, RequestOptions.none())

    /** @see list */
    fun list(requestOptions: RequestOptions): List<UrlEndpointListResponse> =
        list(UrlEndpointListParams.none(), requestOptions)

    /**
     * **Note:** This API is currently in beta. Deletes the URL‑endpoint identified by `id`. You
     * cannot delete the default URL‑endpoint created by ImageKit during account creation.
     */
    fun delete(id: String) = delete(id, UrlEndpointDeleteParams.none())

    /** @see delete */
    fun delete(
        id: String,
        params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ) = delete(params.toBuilder().id(id).build(), requestOptions)

    /** @see delete */
    fun delete(id: String, params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none()) =
        delete(id, params, RequestOptions.none())

    /** @see delete */
    fun delete(
        params: UrlEndpointDeleteParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    )

    /** @see delete */
    fun delete(params: UrlEndpointDeleteParams) = delete(params, RequestOptions.none())

    /** @see delete */
    fun delete(id: String, requestOptions: RequestOptions) =
        delete(id, UrlEndpointDeleteParams.none(), requestOptions)

    /** **Note:** This API is currently in beta. Retrieves the URL‑endpoint identified by `id`. */
    fun get(id: String): UrlEndpointGetResponse = get(id, UrlEndpointGetParams.none())

    /** @see get */
    fun get(
        id: String,
        params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointGetResponse = get(params.toBuilder().id(id).build(), requestOptions)

    /** @see get */
    fun get(
        id: String,
        params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
    ): UrlEndpointGetResponse = get(id, params, RequestOptions.none())

    /** @see get */
    fun get(
        params: UrlEndpointGetParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointGetResponse

    /** @see get */
    fun get(params: UrlEndpointGetParams): UrlEndpointGetResponse =
        get(params, RequestOptions.none())

    /** @see get */
    fun get(id: String, requestOptions: RequestOptions): UrlEndpointGetResponse =
        get(id, UrlEndpointGetParams.none(), requestOptions)

    /**
     * A view of [UrlEndpointService] that provides access to raw HTTP responses for each method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): UrlEndpointService.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /v1/accounts/url-endpoints`, but is otherwise the
         * same as [UrlEndpointService.create].
         */
        @MustBeClosed
        fun create(params: UrlEndpointCreateParams): HttpResponseFor<UrlEndpointCreateResponse> =
            create(params, RequestOptions.none())

        /** @see create */
        @MustBeClosed
        fun create(
            params: UrlEndpointCreateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointCreateResponse>

        /**
         * Returns a raw HTTP response for `put /v1/accounts/url-endpoints/{id}`, but is otherwise
         * the same as [UrlEndpointService.update].
         */
        @MustBeClosed
        fun update(
            id: String,
            params: UrlEndpointUpdateParams,
        ): HttpResponseFor<UrlEndpointUpdateResponse> = update(id, params, RequestOptions.none())

        /** @see update */
        @MustBeClosed
        fun update(
            id: String,
            params: UrlEndpointUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointUpdateResponse> =
            update(params.toBuilder().id(id).build(), requestOptions)

        /** @see update */
        @MustBeClosed
        fun update(params: UrlEndpointUpdateParams): HttpResponseFor<UrlEndpointUpdateResponse> =
            update(params, RequestOptions.none())

        /** @see update */
        @MustBeClosed
        fun update(
            params: UrlEndpointUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointUpdateResponse>

        /**
         * Returns a raw HTTP response for `get /v1/accounts/url-endpoints`, but is otherwise the
         * same as [UrlEndpointService.list].
         */
        @MustBeClosed
        fun list(): HttpResponseFor<List<UrlEndpointListResponse>> =
            list(UrlEndpointListParams.none())

        /** @see list */
        @MustBeClosed
        fun list(
            params: UrlEndpointListParams = UrlEndpointListParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<List<UrlEndpointListResponse>>

        /** @see list */
        @MustBeClosed
        fun list(
            params: UrlEndpointListParams = UrlEndpointListParams.none()
        ): HttpResponseFor<List<UrlEndpointListResponse>> = list(params, RequestOptions.none())

        /** @see list */
        @MustBeClosed
        fun list(requestOptions: RequestOptions): HttpResponseFor<List<UrlEndpointListResponse>> =
            list(UrlEndpointListParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `delete /v1/accounts/url-endpoints/{id}`, but is
         * otherwise the same as [UrlEndpointService.delete].
         */
        @MustBeClosed
        fun delete(id: String): HttpResponse = delete(id, UrlEndpointDeleteParams.none())

        /** @see delete */
        @MustBeClosed
        fun delete(
            id: String,
            params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponse = delete(params.toBuilder().id(id).build(), requestOptions)

        /** @see delete */
        @MustBeClosed
        fun delete(
            id: String,
            params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none(),
        ): HttpResponse = delete(id, params, RequestOptions.none())

        /** @see delete */
        @MustBeClosed
        fun delete(
            params: UrlEndpointDeleteParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponse

        /** @see delete */
        @MustBeClosed
        fun delete(params: UrlEndpointDeleteParams): HttpResponse =
            delete(params, RequestOptions.none())

        /** @see delete */
        @MustBeClosed
        fun delete(id: String, requestOptions: RequestOptions): HttpResponse =
            delete(id, UrlEndpointDeleteParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `get /v1/accounts/url-endpoints/{id}`, but is otherwise
         * the same as [UrlEndpointService.get].
         */
        @MustBeClosed
        fun get(id: String): HttpResponseFor<UrlEndpointGetResponse> =
            get(id, UrlEndpointGetParams.none())

        /** @see get */
        @MustBeClosed
        fun get(
            id: String,
            params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointGetResponse> =
            get(params.toBuilder().id(id).build(), requestOptions)

        /** @see get */
        @MustBeClosed
        fun get(
            id: String,
            params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
        ): HttpResponseFor<UrlEndpointGetResponse> = get(id, params, RequestOptions.none())

        /** @see get */
        @MustBeClosed
        fun get(
            params: UrlEndpointGetParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointGetResponse>

        /** @see get */
        @MustBeClosed
        fun get(params: UrlEndpointGetParams): HttpResponseFor<UrlEndpointGetResponse> =
            get(params, RequestOptions.none())

        /** @see get */
        @MustBeClosed
        fun get(
            id: String,
            requestOptions: RequestOptions,
        ): HttpResponseFor<UrlEndpointGetResponse> =
            get(id, UrlEndpointGetParams.none(), requestOptions)
    }
}
