// File generated from our OpenAPI spec by Stainless.

package com.imagekit.api.services.async.accounts

import com.imagekit.api.core.ClientOptions
import com.imagekit.api.core.RequestOptions
import com.imagekit.api.core.http.HttpResponse
import com.imagekit.api.core.http.HttpResponseFor
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointCreateParams
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointCreateResponse
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointDeleteParams
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointGetParams
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointGetResponse
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointListParams
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointListResponse
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointUpdateParams
import com.imagekit.api.models.accounts.urlendpoints.UrlEndpointUpdateResponse
import java.util.concurrent.CompletableFuture
import java.util.function.Consumer

interface UrlEndpointServiceAsync {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): UrlEndpointServiceAsync

    /**
     * **Note:** This API is currently in beta. Creates a new URL‑endpoint and returns the resulting
     * object.
     */
    fun create(params: UrlEndpointCreateParams): CompletableFuture<UrlEndpointCreateResponse> =
        create(params, RequestOptions.none())

    /** @see create */
    fun create(
        params: UrlEndpointCreateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<UrlEndpointCreateResponse>

    /**
     * **Note:** This API is currently in beta. Updates the URL‑endpoint identified by `id` and
     * returns the updated object.
     */
    fun update(
        id: String,
        params: UrlEndpointUpdateParams,
    ): CompletableFuture<UrlEndpointUpdateResponse> = update(id, params, RequestOptions.none())

    /** @see update */
    fun update(
        id: String,
        params: UrlEndpointUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<UrlEndpointUpdateResponse> =
        update(params.toBuilder().id(id).build(), requestOptions)

    /** @see update */
    fun update(params: UrlEndpointUpdateParams): CompletableFuture<UrlEndpointUpdateResponse> =
        update(params, RequestOptions.none())

    /** @see update */
    fun update(
        params: UrlEndpointUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<UrlEndpointUpdateResponse>

    /**
     * **Note:** This API is currently in beta. Returns an array of all URL‑endpoints configured
     * including the default URL-endpoint generated by ImageKit during account creation.
     */
    fun list(): CompletableFuture<List<UrlEndpointListResponse>> =
        list(UrlEndpointListParams.none())

    /** @see list */
    fun list(
        params: UrlEndpointListParams = UrlEndpointListParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<List<UrlEndpointListResponse>>

    /** @see list */
    fun list(
        params: UrlEndpointListParams = UrlEndpointListParams.none()
    ): CompletableFuture<List<UrlEndpointListResponse>> = list(params, RequestOptions.none())

    /** @see list */
    fun list(requestOptions: RequestOptions): CompletableFuture<List<UrlEndpointListResponse>> =
        list(UrlEndpointListParams.none(), requestOptions)

    /**
     * **Note:** This API is currently in beta. Deletes the URL‑endpoint identified by `id`. You
     * cannot delete the default URL‑endpoint created by ImageKit during account creation.
     */
    fun delete(id: String): CompletableFuture<Void?> = delete(id, UrlEndpointDeleteParams.none())

    /** @see delete */
    fun delete(
        id: String,
        params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Void?> = delete(params.toBuilder().id(id).build(), requestOptions)

    /** @see delete */
    fun delete(
        id: String,
        params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none(),
    ): CompletableFuture<Void?> = delete(id, params, RequestOptions.none())

    /** @see delete */
    fun delete(
        params: UrlEndpointDeleteParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<Void?>

    /** @see delete */
    fun delete(params: UrlEndpointDeleteParams): CompletableFuture<Void?> =
        delete(params, RequestOptions.none())

    /** @see delete */
    fun delete(id: String, requestOptions: RequestOptions): CompletableFuture<Void?> =
        delete(id, UrlEndpointDeleteParams.none(), requestOptions)

    /** **Note:** This API is currently in beta. Retrieves the URL‑endpoint identified by `id`. */
    fun get(id: String): CompletableFuture<UrlEndpointGetResponse> =
        get(id, UrlEndpointGetParams.none())

    /** @see get */
    fun get(
        id: String,
        params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<UrlEndpointGetResponse> =
        get(params.toBuilder().id(id).build(), requestOptions)

    /** @see get */
    fun get(
        id: String,
        params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
    ): CompletableFuture<UrlEndpointGetResponse> = get(id, params, RequestOptions.none())

    /** @see get */
    fun get(
        params: UrlEndpointGetParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): CompletableFuture<UrlEndpointGetResponse>

    /** @see get */
    fun get(params: UrlEndpointGetParams): CompletableFuture<UrlEndpointGetResponse> =
        get(params, RequestOptions.none())

    /** @see get */
    fun get(id: String, requestOptions: RequestOptions): CompletableFuture<UrlEndpointGetResponse> =
        get(id, UrlEndpointGetParams.none(), requestOptions)

    /**
     * A view of [UrlEndpointServiceAsync] that provides access to raw HTTP responses for each
     * method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): UrlEndpointServiceAsync.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /v1/accounts/url-endpoints`, but is otherwise the
         * same as [UrlEndpointServiceAsync.create].
         */
        fun create(
            params: UrlEndpointCreateParams
        ): CompletableFuture<HttpResponseFor<UrlEndpointCreateResponse>> =
            create(params, RequestOptions.none())

        /** @see create */
        fun create(
            params: UrlEndpointCreateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<UrlEndpointCreateResponse>>

        /**
         * Returns a raw HTTP response for `put /v1/accounts/url-endpoints/{id}`, but is otherwise
         * the same as [UrlEndpointServiceAsync.update].
         */
        fun update(
            id: String,
            params: UrlEndpointUpdateParams,
        ): CompletableFuture<HttpResponseFor<UrlEndpointUpdateResponse>> =
            update(id, params, RequestOptions.none())

        /** @see update */
        fun update(
            id: String,
            params: UrlEndpointUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<UrlEndpointUpdateResponse>> =
            update(params.toBuilder().id(id).build(), requestOptions)

        /** @see update */
        fun update(
            params: UrlEndpointUpdateParams
        ): CompletableFuture<HttpResponseFor<UrlEndpointUpdateResponse>> =
            update(params, RequestOptions.none())

        /** @see update */
        fun update(
            params: UrlEndpointUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<UrlEndpointUpdateResponse>>

        /**
         * Returns a raw HTTP response for `get /v1/accounts/url-endpoints`, but is otherwise the
         * same as [UrlEndpointServiceAsync.list].
         */
        fun list(): CompletableFuture<HttpResponseFor<List<UrlEndpointListResponse>>> =
            list(UrlEndpointListParams.none())

        /** @see list */
        fun list(
            params: UrlEndpointListParams = UrlEndpointListParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<List<UrlEndpointListResponse>>>

        /** @see list */
        fun list(
            params: UrlEndpointListParams = UrlEndpointListParams.none()
        ): CompletableFuture<HttpResponseFor<List<UrlEndpointListResponse>>> =
            list(params, RequestOptions.none())

        /** @see list */
        fun list(
            requestOptions: RequestOptions
        ): CompletableFuture<HttpResponseFor<List<UrlEndpointListResponse>>> =
            list(UrlEndpointListParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `delete /v1/accounts/url-endpoints/{id}`, but is
         * otherwise the same as [UrlEndpointServiceAsync.delete].
         */
        fun delete(id: String): CompletableFuture<HttpResponse> =
            delete(id, UrlEndpointDeleteParams.none())

        /** @see delete */
        fun delete(
            id: String,
            params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponse> =
            delete(params.toBuilder().id(id).build(), requestOptions)

        /** @see delete */
        fun delete(
            id: String,
            params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none(),
        ): CompletableFuture<HttpResponse> = delete(id, params, RequestOptions.none())

        /** @see delete */
        fun delete(
            params: UrlEndpointDeleteParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponse>

        /** @see delete */
        fun delete(params: UrlEndpointDeleteParams): CompletableFuture<HttpResponse> =
            delete(params, RequestOptions.none())

        /** @see delete */
        fun delete(id: String, requestOptions: RequestOptions): CompletableFuture<HttpResponse> =
            delete(id, UrlEndpointDeleteParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `get /v1/accounts/url-endpoints/{id}`, but is otherwise
         * the same as [UrlEndpointServiceAsync.get].
         */
        fun get(id: String): CompletableFuture<HttpResponseFor<UrlEndpointGetResponse>> =
            get(id, UrlEndpointGetParams.none())

        /** @see get */
        fun get(
            id: String,
            params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<UrlEndpointGetResponse>> =
            get(params.toBuilder().id(id).build(), requestOptions)

        /** @see get */
        fun get(
            id: String,
            params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
        ): CompletableFuture<HttpResponseFor<UrlEndpointGetResponse>> =
            get(id, params, RequestOptions.none())

        /** @see get */
        fun get(
            params: UrlEndpointGetParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): CompletableFuture<HttpResponseFor<UrlEndpointGetResponse>>

        /** @see get */
        fun get(
            params: UrlEndpointGetParams
        ): CompletableFuture<HttpResponseFor<UrlEndpointGetResponse>> =
            get(params, RequestOptions.none())

        /** @see get */
        fun get(
            id: String,
            requestOptions: RequestOptions,
        ): CompletableFuture<HttpResponseFor<UrlEndpointGetResponse>> =
            get(id, UrlEndpointGetParams.none(), requestOptions)
    }
}
