// File generated from our OpenAPI spec by Stainless.

package com.imagekit.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.imagekit.api.core.JsonValue
import com.imagekit.api.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SrcOptionsTest {

    @Test
    fun create() {
        val srcOptions =
            SrcOptions.builder()
                .src("/my-image.jpg")
                .urlEndpoint("https://ik.imagekit.io/demo")
                .queryParameters(
                    SrcOptions.QueryParameters.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .addTransformation(
                    Transformation.builder()
                        .aiChangeBackground("aiChangeBackground")
                        .aiDropShadow(Transformation.AiDropShadow.UnionMember0.TRUE)
                        .aiRemoveBackground(Transformation.AiRemoveBackground.TRUE)
                        .aiRemoveBackgroundExternal(Transformation.AiRemoveBackgroundExternal.TRUE)
                        .aiRetouch(Transformation.AiRetouch.TRUE)
                        .aiUpscale(Transformation.AiUpscale.TRUE)
                        .aiVariation(Transformation.AiVariation.TRUE)
                        .aspectRatio("4:3")
                        .audioCodec(Transformation.AudioCodec.AAC)
                        .background("red")
                        .blur(10.0)
                        .border("5_FF0000")
                        .colorProfile(true)
                        .contrastStretch(Transformation.ContrastStretch.TRUE)
                        .crop(Transformation.Crop.FORCE)
                        .cropMode(Transformation.CropMode.PAD_RESIZE)
                        .defaultImage("defaultImage")
                        .dpr(2.0)
                        .duration(0.0)
                        .endOffset(0.0)
                        .flip(Transformation.Flip.H)
                        .focus("center")
                        .format(Transformation.Format.AUTO)
                        .gradient(Transformation.Gradient.UnionMember0.TRUE)
                        .grayscale(Transformation.Grayscale.TRUE)
                        .height(200.0)
                        .lossless(true)
                        .metadata(true)
                        .named("named")
                        .opacity(0.0)
                        .original(true)
                        .page(0.0)
                        .progressive(true)
                        .quality(80.0)
                        .radius(20.0)
                        .raw("raw")
                        .rotation(90.0)
                        .shadow(Transformation.Shadow.UnionMember0.TRUE)
                        .sharpen(Transformation.Sharpen.UnionMember0.TRUE)
                        .startOffset(0.0)
                        .addStreamingResolution(StreamingResolution._240)
                        .trim(Transformation.Trim.UnionMember0.TRUE)
                        .unsharpMask(Transformation.UnsharpMask.UnionMember0.TRUE)
                        .videoCodec(Transformation.VideoCodec.H264)
                        .width(300.0)
                        .x(0.0)
                        .xCenter(0.0)
                        .y(0.0)
                        .yCenter(0.0)
                        .zoom(0.0)
                        .build()
                )
                .transformationPosition(TransformationPosition.PATH)
                .build()

        assertThat(srcOptions.src()).isEqualTo("/my-image.jpg")
        assertThat(srcOptions.urlEndpoint()).isEqualTo("https://ik.imagekit.io/demo")
        assertThat(srcOptions.queryParameters())
            .contains(
                SrcOptions.QueryParameters.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(srcOptions.transformation().getOrNull())
            .containsExactly(
                Transformation.builder()
                    .aiChangeBackground("aiChangeBackground")
                    .aiDropShadow(Transformation.AiDropShadow.UnionMember0.TRUE)
                    .aiRemoveBackground(Transformation.AiRemoveBackground.TRUE)
                    .aiRemoveBackgroundExternal(Transformation.AiRemoveBackgroundExternal.TRUE)
                    .aiRetouch(Transformation.AiRetouch.TRUE)
                    .aiUpscale(Transformation.AiUpscale.TRUE)
                    .aiVariation(Transformation.AiVariation.TRUE)
                    .aspectRatio("4:3")
                    .audioCodec(Transformation.AudioCodec.AAC)
                    .background("red")
                    .blur(10.0)
                    .border("5_FF0000")
                    .colorProfile(true)
                    .contrastStretch(Transformation.ContrastStretch.TRUE)
                    .crop(Transformation.Crop.FORCE)
                    .cropMode(Transformation.CropMode.PAD_RESIZE)
                    .defaultImage("defaultImage")
                    .dpr(2.0)
                    .duration(0.0)
                    .endOffset(0.0)
                    .flip(Transformation.Flip.H)
                    .focus("center")
                    .format(Transformation.Format.AUTO)
                    .gradient(Transformation.Gradient.UnionMember0.TRUE)
                    .grayscale(Transformation.Grayscale.TRUE)
                    .height(200.0)
                    .lossless(true)
                    .metadata(true)
                    .named("named")
                    .opacity(0.0)
                    .original(true)
                    .page(0.0)
                    .progressive(true)
                    .quality(80.0)
                    .radius(20.0)
                    .raw("raw")
                    .rotation(90.0)
                    .shadow(Transformation.Shadow.UnionMember0.TRUE)
                    .sharpen(Transformation.Sharpen.UnionMember0.TRUE)
                    .startOffset(0.0)
                    .addStreamingResolution(StreamingResolution._240)
                    .trim(Transformation.Trim.UnionMember0.TRUE)
                    .unsharpMask(Transformation.UnsharpMask.UnionMember0.TRUE)
                    .videoCodec(Transformation.VideoCodec.H264)
                    .width(300.0)
                    .x(0.0)
                    .xCenter(0.0)
                    .y(0.0)
                    .yCenter(0.0)
                    .zoom(0.0)
                    .build()
            )
        assertThat(srcOptions.transformationPosition()).contains(TransformationPosition.PATH)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val srcOptions =
            SrcOptions.builder()
                .src("/my-image.jpg")
                .urlEndpoint("https://ik.imagekit.io/demo")
                .queryParameters(
                    SrcOptions.QueryParameters.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .addTransformation(
                    Transformation.builder()
                        .aiChangeBackground("aiChangeBackground")
                        .aiDropShadow(Transformation.AiDropShadow.UnionMember0.TRUE)
                        .aiRemoveBackground(Transformation.AiRemoveBackground.TRUE)
                        .aiRemoveBackgroundExternal(Transformation.AiRemoveBackgroundExternal.TRUE)
                        .aiRetouch(Transformation.AiRetouch.TRUE)
                        .aiUpscale(Transformation.AiUpscale.TRUE)
                        .aiVariation(Transformation.AiVariation.TRUE)
                        .aspectRatio("4:3")
                        .audioCodec(Transformation.AudioCodec.AAC)
                        .background("red")
                        .blur(10.0)
                        .border("5_FF0000")
                        .colorProfile(true)
                        .contrastStretch(Transformation.ContrastStretch.TRUE)
                        .crop(Transformation.Crop.FORCE)
                        .cropMode(Transformation.CropMode.PAD_RESIZE)
                        .defaultImage("defaultImage")
                        .dpr(2.0)
                        .duration(0.0)
                        .endOffset(0.0)
                        .flip(Transformation.Flip.H)
                        .focus("center")
                        .format(Transformation.Format.AUTO)
                        .gradient(Transformation.Gradient.UnionMember0.TRUE)
                        .grayscale(Transformation.Grayscale.TRUE)
                        .height(200.0)
                        .lossless(true)
                        .metadata(true)
                        .named("named")
                        .opacity(0.0)
                        .original(true)
                        .page(0.0)
                        .progressive(true)
                        .quality(80.0)
                        .radius(20.0)
                        .raw("raw")
                        .rotation(90.0)
                        .shadow(Transformation.Shadow.UnionMember0.TRUE)
                        .sharpen(Transformation.Sharpen.UnionMember0.TRUE)
                        .startOffset(0.0)
                        .addStreamingResolution(StreamingResolution._240)
                        .trim(Transformation.Trim.UnionMember0.TRUE)
                        .unsharpMask(Transformation.UnsharpMask.UnionMember0.TRUE)
                        .videoCodec(Transformation.VideoCodec.H264)
                        .width(300.0)
                        .x(0.0)
                        .xCenter(0.0)
                        .y(0.0)
                        .yCenter(0.0)
                        .zoom(0.0)
                        .build()
                )
                .transformationPosition(TransformationPosition.PATH)
                .build()

        val roundtrippedSrcOptions =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(srcOptions),
                jacksonTypeRef<SrcOptions>(),
            )

        assertThat(roundtrippedSrcOptions).isEqualTo(srcOptions)
    }
}
