// File generated from our OpenAPI spec by Stainless.

package io.imagekit.models.webhooks

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import io.imagekit.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class VideoTransformationReadyEventTest {

    @Test
    fun create() {
        val videoTransformationReadyEvent =
            VideoTransformationReadyEvent.builder()
                .id("id")
                .type("video.transformation.ready")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .data(
                    VideoTransformationReadyEvent.Data.builder()
                        .asset(
                            VideoTransformationReadyEvent.Data.Asset.builder()
                                .url("https://example.com")
                                .build()
                        )
                        .transformation(
                            VideoTransformationReadyEvent.Data.Transformation.builder()
                                .type(
                                    VideoTransformationReadyEvent.Data.Transformation.Type
                                        .VIDEO_TRANSFORMATION
                                )
                                .options(
                                    VideoTransformationReadyEvent.Data.Transformation.Options
                                        .builder()
                                        .audioCodec(
                                            VideoTransformationReadyEvent.Data.Transformation
                                                .Options
                                                .AudioCodec
                                                .AAC
                                        )
                                        .autoRotate(true)
                                        .format(
                                            VideoTransformationReadyEvent.Data.Transformation
                                                .Options
                                                .Format
                                                .MP4
                                        )
                                        .quality(0L)
                                        .streamProtocol(
                                            VideoTransformationReadyEvent.Data.Transformation
                                                .Options
                                                .StreamProtocol
                                                .HLS
                                        )
                                        .addVariant("string")
                                        .videoCodec(
                                            VideoTransformationReadyEvent.Data.Transformation
                                                .Options
                                                .VideoCodec
                                                .H264
                                        )
                                        .build()
                                )
                                .output(
                                    VideoTransformationReadyEvent.Data.Transformation.Output
                                        .builder()
                                        .url("https://example.com")
                                        .videoMetadata(
                                            VideoTransformationReadyEvent.Data.Transformation.Output
                                                .VideoMetadata
                                                .builder()
                                                .bitrate(0L)
                                                .duration(0.0)
                                                .height(0L)
                                                .width(0L)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .request(
                    VideoTransformationReadyEvent.Request.builder()
                        .url("https://example.com")
                        .xRequestId("x_request_id")
                        .userAgent("user_agent")
                        .build()
                )
                .timings(
                    VideoTransformationReadyEvent.Timings.builder()
                        .downloadDuration(0L)
                        .encodingDuration(0L)
                        .build()
                )
                .build()

        assertThat(videoTransformationReadyEvent.id()).isEqualTo("id")
        assertThat(videoTransformationReadyEvent.type()).isEqualTo("video.transformation.ready")
        assertThat(videoTransformationReadyEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(videoTransformationReadyEvent.data())
            .isEqualTo(
                VideoTransformationReadyEvent.Data.builder()
                    .asset(
                        VideoTransformationReadyEvent.Data.Asset.builder()
                            .url("https://example.com")
                            .build()
                    )
                    .transformation(
                        VideoTransformationReadyEvent.Data.Transformation.builder()
                            .type(
                                VideoTransformationReadyEvent.Data.Transformation.Type
                                    .VIDEO_TRANSFORMATION
                            )
                            .options(
                                VideoTransformationReadyEvent.Data.Transformation.Options.builder()
                                    .audioCodec(
                                        VideoTransformationReadyEvent.Data.Transformation.Options
                                            .AudioCodec
                                            .AAC
                                    )
                                    .autoRotate(true)
                                    .format(
                                        VideoTransformationReadyEvent.Data.Transformation.Options
                                            .Format
                                            .MP4
                                    )
                                    .quality(0L)
                                    .streamProtocol(
                                        VideoTransformationReadyEvent.Data.Transformation.Options
                                            .StreamProtocol
                                            .HLS
                                    )
                                    .addVariant("string")
                                    .videoCodec(
                                        VideoTransformationReadyEvent.Data.Transformation.Options
                                            .VideoCodec
                                            .H264
                                    )
                                    .build()
                            )
                            .output(
                                VideoTransformationReadyEvent.Data.Transformation.Output.builder()
                                    .url("https://example.com")
                                    .videoMetadata(
                                        VideoTransformationReadyEvent.Data.Transformation.Output
                                            .VideoMetadata
                                            .builder()
                                            .bitrate(0L)
                                            .duration(0.0)
                                            .height(0L)
                                            .width(0L)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(videoTransformationReadyEvent.request())
            .isEqualTo(
                VideoTransformationReadyEvent.Request.builder()
                    .url("https://example.com")
                    .xRequestId("x_request_id")
                    .userAgent("user_agent")
                    .build()
            )
        assertThat(videoTransformationReadyEvent.timings())
            .contains(
                VideoTransformationReadyEvent.Timings.builder()
                    .downloadDuration(0L)
                    .encodingDuration(0L)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val videoTransformationReadyEvent =
            VideoTransformationReadyEvent.builder()
                .id("id")
                .type("video.transformation.ready")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .data(
                    VideoTransformationReadyEvent.Data.builder()
                        .asset(
                            VideoTransformationReadyEvent.Data.Asset.builder()
                                .url("https://example.com")
                                .build()
                        )
                        .transformation(
                            VideoTransformationReadyEvent.Data.Transformation.builder()
                                .type(
                                    VideoTransformationReadyEvent.Data.Transformation.Type
                                        .VIDEO_TRANSFORMATION
                                )
                                .options(
                                    VideoTransformationReadyEvent.Data.Transformation.Options
                                        .builder()
                                        .audioCodec(
                                            VideoTransformationReadyEvent.Data.Transformation
                                                .Options
                                                .AudioCodec
                                                .AAC
                                        )
                                        .autoRotate(true)
                                        .format(
                                            VideoTransformationReadyEvent.Data.Transformation
                                                .Options
                                                .Format
                                                .MP4
                                        )
                                        .quality(0L)
                                        .streamProtocol(
                                            VideoTransformationReadyEvent.Data.Transformation
                                                .Options
                                                .StreamProtocol
                                                .HLS
                                        )
                                        .addVariant("string")
                                        .videoCodec(
                                            VideoTransformationReadyEvent.Data.Transformation
                                                .Options
                                                .VideoCodec
                                                .H264
                                        )
                                        .build()
                                )
                                .output(
                                    VideoTransformationReadyEvent.Data.Transformation.Output
                                        .builder()
                                        .url("https://example.com")
                                        .videoMetadata(
                                            VideoTransformationReadyEvent.Data.Transformation.Output
                                                .VideoMetadata
                                                .builder()
                                                .bitrate(0L)
                                                .duration(0.0)
                                                .height(0L)
                                                .width(0L)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .request(
                    VideoTransformationReadyEvent.Request.builder()
                        .url("https://example.com")
                        .xRequestId("x_request_id")
                        .userAgent("user_agent")
                        .build()
                )
                .timings(
                    VideoTransformationReadyEvent.Timings.builder()
                        .downloadDuration(0L)
                        .encodingDuration(0L)
                        .build()
                )
                .build()

        val roundtrippedVideoTransformationReadyEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(videoTransformationReadyEvent),
                jacksonTypeRef<VideoTransformationReadyEvent>(),
            )

        assertThat(roundtrippedVideoTransformationReadyEvent)
            .isEqualTo(videoTransformationReadyEvent)
    }
}
