// File generated from our OpenAPI spec by Stainless.

package io.imagekit.io.services.blocking.accounts

import com.google.errorprone.annotations.MustBeClosed
import io.imagekit.io.core.ClientOptions
import io.imagekit.io.core.RequestOptions
import io.imagekit.io.core.http.HttpResponse
import io.imagekit.io.core.http.HttpResponseFor
import io.imagekit.io.models.accounts.urlendpoints.UrlEndpointCreateParams
import io.imagekit.io.models.accounts.urlendpoints.UrlEndpointDeleteParams
import io.imagekit.io.models.accounts.urlendpoints.UrlEndpointGetParams
import io.imagekit.io.models.accounts.urlendpoints.UrlEndpointListParams
import io.imagekit.io.models.accounts.urlendpoints.UrlEndpointRequest
import io.imagekit.io.models.accounts.urlendpoints.UrlEndpointResponse
import io.imagekit.io.models.accounts.urlendpoints.UrlEndpointUpdateParams
import java.util.function.Consumer

interface UrlEndpointService {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): UrlEndpointService

    /**
     * **Note:** This API is currently in beta. Creates a new URL‑endpoint and returns the resulting
     * object.
     */
    fun create(params: UrlEndpointCreateParams): UrlEndpointResponse =
        create(params, RequestOptions.none())

    /** @see create */
    fun create(
        params: UrlEndpointCreateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointResponse

    /** @see create */
    fun create(
        urlEndpointRequest: UrlEndpointRequest,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointResponse =
        create(
            UrlEndpointCreateParams.builder().urlEndpointRequest(urlEndpointRequest).build(),
            requestOptions,
        )

    /** @see create */
    fun create(urlEndpointRequest: UrlEndpointRequest): UrlEndpointResponse =
        create(urlEndpointRequest, RequestOptions.none())

    /**
     * **Note:** This API is currently in beta. Updates the URL‑endpoint identified by `id` and
     * returns the updated object.
     */
    fun update(id: String, params: UrlEndpointUpdateParams): UrlEndpointResponse =
        update(id, params, RequestOptions.none())

    /** @see update */
    fun update(
        id: String,
        params: UrlEndpointUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointResponse = update(params.toBuilder().id(id).build(), requestOptions)

    /** @see update */
    fun update(params: UrlEndpointUpdateParams): UrlEndpointResponse =
        update(params, RequestOptions.none())

    /** @see update */
    fun update(
        params: UrlEndpointUpdateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointResponse

    /**
     * **Note:** This API is currently in beta. Returns an array of all URL‑endpoints configured
     * including the default URL-endpoint generated by ImageKit during account creation.
     */
    fun list(): List<UrlEndpointResponse> = list(UrlEndpointListParams.none())

    /** @see list */
    fun list(
        params: UrlEndpointListParams = UrlEndpointListParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): List<UrlEndpointResponse>

    /** @see list */
    fun list(
        params: UrlEndpointListParams = UrlEndpointListParams.none()
    ): List<UrlEndpointResponse> = list(params, RequestOptions.none())

    /** @see list */
    fun list(requestOptions: RequestOptions): List<UrlEndpointResponse> =
        list(UrlEndpointListParams.none(), requestOptions)

    /**
     * **Note:** This API is currently in beta. Deletes the URL‑endpoint identified by `id`. You
     * cannot delete the default URL‑endpoint created by ImageKit during account creation.
     */
    fun delete(id: String) = delete(id, UrlEndpointDeleteParams.none())

    /** @see delete */
    fun delete(
        id: String,
        params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ) = delete(params.toBuilder().id(id).build(), requestOptions)

    /** @see delete */
    fun delete(id: String, params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none()) =
        delete(id, params, RequestOptions.none())

    /** @see delete */
    fun delete(
        params: UrlEndpointDeleteParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    )

    /** @see delete */
    fun delete(params: UrlEndpointDeleteParams) = delete(params, RequestOptions.none())

    /** @see delete */
    fun delete(id: String, requestOptions: RequestOptions) =
        delete(id, UrlEndpointDeleteParams.none(), requestOptions)

    /** **Note:** This API is currently in beta. Retrieves the URL‑endpoint identified by `id`. */
    fun get(id: String): UrlEndpointResponse = get(id, UrlEndpointGetParams.none())

    /** @see get */
    fun get(
        id: String,
        params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointResponse = get(params.toBuilder().id(id).build(), requestOptions)

    /** @see get */
    fun get(
        id: String,
        params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
    ): UrlEndpointResponse = get(id, params, RequestOptions.none())

    /** @see get */
    fun get(
        params: UrlEndpointGetParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): UrlEndpointResponse

    /** @see get */
    fun get(params: UrlEndpointGetParams): UrlEndpointResponse = get(params, RequestOptions.none())

    /** @see get */
    fun get(id: String, requestOptions: RequestOptions): UrlEndpointResponse =
        get(id, UrlEndpointGetParams.none(), requestOptions)

    /**
     * A view of [UrlEndpointService] that provides access to raw HTTP responses for each method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): UrlEndpointService.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /v1/accounts/url-endpoints`, but is otherwise the
         * same as [UrlEndpointService.create].
         */
        @MustBeClosed
        fun create(params: UrlEndpointCreateParams): HttpResponseFor<UrlEndpointResponse> =
            create(params, RequestOptions.none())

        /** @see create */
        @MustBeClosed
        fun create(
            params: UrlEndpointCreateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointResponse>

        /** @see create */
        @MustBeClosed
        fun create(
            urlEndpointRequest: UrlEndpointRequest,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointResponse> =
            create(
                UrlEndpointCreateParams.builder().urlEndpointRequest(urlEndpointRequest).build(),
                requestOptions,
            )

        /** @see create */
        @MustBeClosed
        fun create(urlEndpointRequest: UrlEndpointRequest): HttpResponseFor<UrlEndpointResponse> =
            create(urlEndpointRequest, RequestOptions.none())

        /**
         * Returns a raw HTTP response for `put /v1/accounts/url-endpoints/{id}`, but is otherwise
         * the same as [UrlEndpointService.update].
         */
        @MustBeClosed
        fun update(
            id: String,
            params: UrlEndpointUpdateParams,
        ): HttpResponseFor<UrlEndpointResponse> = update(id, params, RequestOptions.none())

        /** @see update */
        @MustBeClosed
        fun update(
            id: String,
            params: UrlEndpointUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointResponse> =
            update(params.toBuilder().id(id).build(), requestOptions)

        /** @see update */
        @MustBeClosed
        fun update(params: UrlEndpointUpdateParams): HttpResponseFor<UrlEndpointResponse> =
            update(params, RequestOptions.none())

        /** @see update */
        @MustBeClosed
        fun update(
            params: UrlEndpointUpdateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointResponse>

        /**
         * Returns a raw HTTP response for `get /v1/accounts/url-endpoints`, but is otherwise the
         * same as [UrlEndpointService.list].
         */
        @MustBeClosed
        fun list(): HttpResponseFor<List<UrlEndpointResponse>> = list(UrlEndpointListParams.none())

        /** @see list */
        @MustBeClosed
        fun list(
            params: UrlEndpointListParams = UrlEndpointListParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<List<UrlEndpointResponse>>

        /** @see list */
        @MustBeClosed
        fun list(
            params: UrlEndpointListParams = UrlEndpointListParams.none()
        ): HttpResponseFor<List<UrlEndpointResponse>> = list(params, RequestOptions.none())

        /** @see list */
        @MustBeClosed
        fun list(requestOptions: RequestOptions): HttpResponseFor<List<UrlEndpointResponse>> =
            list(UrlEndpointListParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `delete /v1/accounts/url-endpoints/{id}`, but is
         * otherwise the same as [UrlEndpointService.delete].
         */
        @MustBeClosed
        fun delete(id: String): HttpResponse = delete(id, UrlEndpointDeleteParams.none())

        /** @see delete */
        @MustBeClosed
        fun delete(
            id: String,
            params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponse = delete(params.toBuilder().id(id).build(), requestOptions)

        /** @see delete */
        @MustBeClosed
        fun delete(
            id: String,
            params: UrlEndpointDeleteParams = UrlEndpointDeleteParams.none(),
        ): HttpResponse = delete(id, params, RequestOptions.none())

        /** @see delete */
        @MustBeClosed
        fun delete(
            params: UrlEndpointDeleteParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponse

        /** @see delete */
        @MustBeClosed
        fun delete(params: UrlEndpointDeleteParams): HttpResponse =
            delete(params, RequestOptions.none())

        /** @see delete */
        @MustBeClosed
        fun delete(id: String, requestOptions: RequestOptions): HttpResponse =
            delete(id, UrlEndpointDeleteParams.none(), requestOptions)

        /**
         * Returns a raw HTTP response for `get /v1/accounts/url-endpoints/{id}`, but is otherwise
         * the same as [UrlEndpointService.get].
         */
        @MustBeClosed
        fun get(id: String): HttpResponseFor<UrlEndpointResponse> =
            get(id, UrlEndpointGetParams.none())

        /** @see get */
        @MustBeClosed
        fun get(
            id: String,
            params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointResponse> =
            get(params.toBuilder().id(id).build(), requestOptions)

        /** @see get */
        @MustBeClosed
        fun get(
            id: String,
            params: UrlEndpointGetParams = UrlEndpointGetParams.none(),
        ): HttpResponseFor<UrlEndpointResponse> = get(id, params, RequestOptions.none())

        /** @see get */
        @MustBeClosed
        fun get(
            params: UrlEndpointGetParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<UrlEndpointResponse>

        /** @see get */
        @MustBeClosed
        fun get(params: UrlEndpointGetParams): HttpResponseFor<UrlEndpointResponse> =
            get(params, RequestOptions.none())

        /** @see get */
        @MustBeClosed
        fun get(id: String, requestOptions: RequestOptions): HttpResponseFor<UrlEndpointResponse> =
            get(id, UrlEndpointGetParams.none(), requestOptions)
    }
}
