// File generated from our OpenAPI spec by Stainless.

package com.imagekit.api.models.webhooks

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.imagekit.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class VideoTransformationErrorWebhookEventTest {

    @Test
    fun create() {
        val videoTransformationErrorWebhookEvent =
            VideoTransformationErrorWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .data(
                    VideoTransformationErrorWebhookEvent.Data.builder()
                        .asset(
                            VideoTransformationErrorWebhookEvent.Data.Asset.builder()
                                .url("https://example.com")
                                .build()
                        )
                        .transformation(
                            VideoTransformationErrorWebhookEvent.Data.Transformation.builder()
                                .type(
                                    VideoTransformationErrorWebhookEvent.Data.Transformation.Type
                                        .VIDEO_TRANSFORMATION
                                )
                                .error(
                                    VideoTransformationErrorWebhookEvent.Data.Transformation.Error
                                        .builder()
                                        .reason(
                                            VideoTransformationErrorWebhookEvent.Data.Transformation
                                                .Error
                                                .Reason
                                                .ENCODING_FAILED
                                        )
                                        .build()
                                )
                                .options(
                                    VideoTransformationErrorWebhookEvent.Data.Transformation.Options
                                        .builder()
                                        .audioCodec(
                                            VideoTransformationErrorWebhookEvent.Data.Transformation
                                                .Options
                                                .AudioCodec
                                                .AAC
                                        )
                                        .autoRotate(true)
                                        .format(
                                            VideoTransformationErrorWebhookEvent.Data.Transformation
                                                .Options
                                                .Format
                                                .MP4
                                        )
                                        .quality(0L)
                                        .streamProtocol(
                                            VideoTransformationErrorWebhookEvent.Data.Transformation
                                                .Options
                                                .StreamProtocol
                                                .HLS
                                        )
                                        .addVariant("string")
                                        .videoCodec(
                                            VideoTransformationErrorWebhookEvent.Data.Transformation
                                                .Options
                                                .VideoCodec
                                                .H264
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .request(
                    VideoTransformationErrorWebhookEvent.Request.builder()
                        .url("https://example.com")
                        .xRequestId("x_request_id")
                        .userAgent("user_agent")
                        .build()
                )
                .build()

        assertThat(videoTransformationErrorWebhookEvent.id()).isEqualTo("id")
        assertThat(videoTransformationErrorWebhookEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(videoTransformationErrorWebhookEvent.data())
            .isEqualTo(
                VideoTransformationErrorWebhookEvent.Data.builder()
                    .asset(
                        VideoTransformationErrorWebhookEvent.Data.Asset.builder()
                            .url("https://example.com")
                            .build()
                    )
                    .transformation(
                        VideoTransformationErrorWebhookEvent.Data.Transformation.builder()
                            .type(
                                VideoTransformationErrorWebhookEvent.Data.Transformation.Type
                                    .VIDEO_TRANSFORMATION
                            )
                            .error(
                                VideoTransformationErrorWebhookEvent.Data.Transformation.Error
                                    .builder()
                                    .reason(
                                        VideoTransformationErrorWebhookEvent.Data.Transformation
                                            .Error
                                            .Reason
                                            .ENCODING_FAILED
                                    )
                                    .build()
                            )
                            .options(
                                VideoTransformationErrorWebhookEvent.Data.Transformation.Options
                                    .builder()
                                    .audioCodec(
                                        VideoTransformationErrorWebhookEvent.Data.Transformation
                                            .Options
                                            .AudioCodec
                                            .AAC
                                    )
                                    .autoRotate(true)
                                    .format(
                                        VideoTransformationErrorWebhookEvent.Data.Transformation
                                            .Options
                                            .Format
                                            .MP4
                                    )
                                    .quality(0L)
                                    .streamProtocol(
                                        VideoTransformationErrorWebhookEvent.Data.Transformation
                                            .Options
                                            .StreamProtocol
                                            .HLS
                                    )
                                    .addVariant("string")
                                    .videoCodec(
                                        VideoTransformationErrorWebhookEvent.Data.Transformation
                                            .Options
                                            .VideoCodec
                                            .H264
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(videoTransformationErrorWebhookEvent.request())
            .isEqualTo(
                VideoTransformationErrorWebhookEvent.Request.builder()
                    .url("https://example.com")
                    .xRequestId("x_request_id")
                    .userAgent("user_agent")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val videoTransformationErrorWebhookEvent =
            VideoTransformationErrorWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .data(
                    VideoTransformationErrorWebhookEvent.Data.builder()
                        .asset(
                            VideoTransformationErrorWebhookEvent.Data.Asset.builder()
                                .url("https://example.com")
                                .build()
                        )
                        .transformation(
                            VideoTransformationErrorWebhookEvent.Data.Transformation.builder()
                                .type(
                                    VideoTransformationErrorWebhookEvent.Data.Transformation.Type
                                        .VIDEO_TRANSFORMATION
                                )
                                .error(
                                    VideoTransformationErrorWebhookEvent.Data.Transformation.Error
                                        .builder()
                                        .reason(
                                            VideoTransformationErrorWebhookEvent.Data.Transformation
                                                .Error
                                                .Reason
                                                .ENCODING_FAILED
                                        )
                                        .build()
                                )
                                .options(
                                    VideoTransformationErrorWebhookEvent.Data.Transformation.Options
                                        .builder()
                                        .audioCodec(
                                            VideoTransformationErrorWebhookEvent.Data.Transformation
                                                .Options
                                                .AudioCodec
                                                .AAC
                                        )
                                        .autoRotate(true)
                                        .format(
                                            VideoTransformationErrorWebhookEvent.Data.Transformation
                                                .Options
                                                .Format
                                                .MP4
                                        )
                                        .quality(0L)
                                        .streamProtocol(
                                            VideoTransformationErrorWebhookEvent.Data.Transformation
                                                .Options
                                                .StreamProtocol
                                                .HLS
                                        )
                                        .addVariant("string")
                                        .videoCodec(
                                            VideoTransformationErrorWebhookEvent.Data.Transformation
                                                .Options
                                                .VideoCodec
                                                .H264
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .request(
                    VideoTransformationErrorWebhookEvent.Request.builder()
                        .url("https://example.com")
                        .xRequestId("x_request_id")
                        .userAgent("user_agent")
                        .build()
                )
                .build()

        val roundtrippedVideoTransformationErrorWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(videoTransformationErrorWebhookEvent),
                jacksonTypeRef<VideoTransformationErrorWebhookEvent>(),
            )

        assertThat(roundtrippedVideoTransformationErrorWebhookEvent)
            .isEqualTo(videoTransformationErrorWebhookEvent)
    }
}
