// File generated from our OpenAPI spec by Stainless.

package com.imagekit.api.models.webhooks

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.imagekit.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class VideoTransformationReadyWebhookEventTest {

    @Test
    fun create() {
        val videoTransformationReadyWebhookEvent =
            VideoTransformationReadyWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .data(
                    VideoTransformationReadyWebhookEvent.Data.builder()
                        .asset(
                            VideoTransformationReadyWebhookEvent.Data.Asset.builder()
                                .url("https://example.com")
                                .build()
                        )
                        .transformation(
                            VideoTransformationReadyWebhookEvent.Data.Transformation.builder()
                                .type(
                                    VideoTransformationReadyWebhookEvent.Data.Transformation.Type
                                        .VIDEO_TRANSFORMATION
                                )
                                .options(
                                    VideoTransformationReadyWebhookEvent.Data.Transformation.Options
                                        .builder()
                                        .audioCodec(
                                            VideoTransformationReadyWebhookEvent.Data.Transformation
                                                .Options
                                                .AudioCodec
                                                .AAC
                                        )
                                        .autoRotate(true)
                                        .format(
                                            VideoTransformationReadyWebhookEvent.Data.Transformation
                                                .Options
                                                .Format
                                                .MP4
                                        )
                                        .quality(0L)
                                        .streamProtocol(
                                            VideoTransformationReadyWebhookEvent.Data.Transformation
                                                .Options
                                                .StreamProtocol
                                                .HLS
                                        )
                                        .addVariant("string")
                                        .videoCodec(
                                            VideoTransformationReadyWebhookEvent.Data.Transformation
                                                .Options
                                                .VideoCodec
                                                .H264
                                        )
                                        .build()
                                )
                                .output(
                                    VideoTransformationReadyWebhookEvent.Data.Transformation.Output
                                        .builder()
                                        .url("https://example.com")
                                        .videoMetadata(
                                            VideoTransformationReadyWebhookEvent.Data.Transformation
                                                .Output
                                                .VideoMetadata
                                                .builder()
                                                .bitrate(0L)
                                                .duration(0.0)
                                                .height(0L)
                                                .width(0L)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .request(
                    VideoTransformationReadyWebhookEvent.Request.builder()
                        .url("https://example.com")
                        .xRequestId("x_request_id")
                        .userAgent("user_agent")
                        .build()
                )
                .timings(
                    VideoTransformationReadyWebhookEvent.Timings.builder()
                        .downloadDuration(0L)
                        .encodingDuration(0L)
                        .build()
                )
                .build()

        assertThat(videoTransformationReadyWebhookEvent.id()).isEqualTo("id")
        assertThat(videoTransformationReadyWebhookEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(videoTransformationReadyWebhookEvent.data())
            .isEqualTo(
                VideoTransformationReadyWebhookEvent.Data.builder()
                    .asset(
                        VideoTransformationReadyWebhookEvent.Data.Asset.builder()
                            .url("https://example.com")
                            .build()
                    )
                    .transformation(
                        VideoTransformationReadyWebhookEvent.Data.Transformation.builder()
                            .type(
                                VideoTransformationReadyWebhookEvent.Data.Transformation.Type
                                    .VIDEO_TRANSFORMATION
                            )
                            .options(
                                VideoTransformationReadyWebhookEvent.Data.Transformation.Options
                                    .builder()
                                    .audioCodec(
                                        VideoTransformationReadyWebhookEvent.Data.Transformation
                                            .Options
                                            .AudioCodec
                                            .AAC
                                    )
                                    .autoRotate(true)
                                    .format(
                                        VideoTransformationReadyWebhookEvent.Data.Transformation
                                            .Options
                                            .Format
                                            .MP4
                                    )
                                    .quality(0L)
                                    .streamProtocol(
                                        VideoTransformationReadyWebhookEvent.Data.Transformation
                                            .Options
                                            .StreamProtocol
                                            .HLS
                                    )
                                    .addVariant("string")
                                    .videoCodec(
                                        VideoTransformationReadyWebhookEvent.Data.Transformation
                                            .Options
                                            .VideoCodec
                                            .H264
                                    )
                                    .build()
                            )
                            .output(
                                VideoTransformationReadyWebhookEvent.Data.Transformation.Output
                                    .builder()
                                    .url("https://example.com")
                                    .videoMetadata(
                                        VideoTransformationReadyWebhookEvent.Data.Transformation
                                            .Output
                                            .VideoMetadata
                                            .builder()
                                            .bitrate(0L)
                                            .duration(0.0)
                                            .height(0L)
                                            .width(0L)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(videoTransformationReadyWebhookEvent.request())
            .isEqualTo(
                VideoTransformationReadyWebhookEvent.Request.builder()
                    .url("https://example.com")
                    .xRequestId("x_request_id")
                    .userAgent("user_agent")
                    .build()
            )
        assertThat(videoTransformationReadyWebhookEvent.timings())
            .contains(
                VideoTransformationReadyWebhookEvent.Timings.builder()
                    .downloadDuration(0L)
                    .encodingDuration(0L)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val videoTransformationReadyWebhookEvent =
            VideoTransformationReadyWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .data(
                    VideoTransformationReadyWebhookEvent.Data.builder()
                        .asset(
                            VideoTransformationReadyWebhookEvent.Data.Asset.builder()
                                .url("https://example.com")
                                .build()
                        )
                        .transformation(
                            VideoTransformationReadyWebhookEvent.Data.Transformation.builder()
                                .type(
                                    VideoTransformationReadyWebhookEvent.Data.Transformation.Type
                                        .VIDEO_TRANSFORMATION
                                )
                                .options(
                                    VideoTransformationReadyWebhookEvent.Data.Transformation.Options
                                        .builder()
                                        .audioCodec(
                                            VideoTransformationReadyWebhookEvent.Data.Transformation
                                                .Options
                                                .AudioCodec
                                                .AAC
                                        )
                                        .autoRotate(true)
                                        .format(
                                            VideoTransformationReadyWebhookEvent.Data.Transformation
                                                .Options
                                                .Format
                                                .MP4
                                        )
                                        .quality(0L)
                                        .streamProtocol(
                                            VideoTransformationReadyWebhookEvent.Data.Transformation
                                                .Options
                                                .StreamProtocol
                                                .HLS
                                        )
                                        .addVariant("string")
                                        .videoCodec(
                                            VideoTransformationReadyWebhookEvent.Data.Transformation
                                                .Options
                                                .VideoCodec
                                                .H264
                                        )
                                        .build()
                                )
                                .output(
                                    VideoTransformationReadyWebhookEvent.Data.Transformation.Output
                                        .builder()
                                        .url("https://example.com")
                                        .videoMetadata(
                                            VideoTransformationReadyWebhookEvent.Data.Transformation
                                                .Output
                                                .VideoMetadata
                                                .builder()
                                                .bitrate(0L)
                                                .duration(0.0)
                                                .height(0L)
                                                .width(0L)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .request(
                    VideoTransformationReadyWebhookEvent.Request.builder()
                        .url("https://example.com")
                        .xRequestId("x_request_id")
                        .userAgent("user_agent")
                        .build()
                )
                .timings(
                    VideoTransformationReadyWebhookEvent.Timings.builder()
                        .downloadDuration(0L)
                        .encodingDuration(0L)
                        .build()
                )
                .build()

        val roundtrippedVideoTransformationReadyWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(videoTransformationReadyWebhookEvent),
                jacksonTypeRef<VideoTransformationReadyWebhookEvent>(),
            )

        assertThat(roundtrippedVideoTransformationReadyWebhookEvent)
            .isEqualTo(videoTransformationReadyWebhookEvent)
    }
}
