// File generated from our OpenAPI spec by Stainless.

package com.imagekit.api.models.files.metadata

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.imagekit.api.core.JsonValue
import com.imagekit.api.core.jsonMapper
import com.imagekit.api.models.files.ExifDetails
import com.imagekit.api.models.files.ExifImage
import com.imagekit.api.models.files.Gps
import com.imagekit.api.models.files.Interoperability
import com.imagekit.api.models.files.Thumbnail
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class MetadataFromUrlResponseTest {

    @Test
    fun create() {
        val metadataFromUrlResponse =
            MetadataFromUrlResponse.builder()
                .audioCodec("audioCodec")
                .bitRate(0L)
                .density(0L)
                .duration(0L)
                .exif(
                    MetadataFromUrlResponse.Exif.builder()
                        .exif(
                            ExifDetails.builder()
                                .apertureValue(0.0)
                                .colorSpace(0L)
                                .createDate("CreateDate")
                                .customRendered(0L)
                                .dateTimeOriginal("DateTimeOriginal")
                                .exifImageHeight(0L)
                                .exifImageWidth(0L)
                                .exifVersion("ExifVersion")
                                .exposureCompensation(0.0)
                                .exposureMode(0L)
                                .exposureProgram(0L)
                                .exposureTime(0.0)
                                .flash(0L)
                                .flashpixVersion("FlashpixVersion")
                                .fNumber(0.0)
                                .focalLength(0L)
                                .focalPlaneResolutionUnit(0L)
                                .focalPlaneXResolution(0.0)
                                .focalPlaneYResolution(0.0)
                                .interopOffset(0L)
                                .iso(0L)
                                .meteringMode(0L)
                                .sceneCaptureType(0L)
                                .shutterSpeedValue(0.0)
                                .subSecTime("SubSecTime")
                                .whiteBalance(0L)
                                .build()
                        )
                        .gps(Gps.builder().addGpsVersionId(0L).build())
                        .image(
                            ExifImage.builder()
                                .exifOffset(0L)
                                .gpsInfo(0L)
                                .make("Make")
                                .model("Model")
                                .modifyDate("ModifyDate")
                                .orientation(0L)
                                .resolutionUnit(0L)
                                .software("Software")
                                .xResolution(0L)
                                .yCbCrPositioning(0L)
                                .yResolution(0L)
                                .build()
                        )
                        .interoperability(
                            Interoperability.builder()
                                .interopIndex("InteropIndex")
                                .interopVersion("InteropVersion")
                                .build()
                        )
                        .makernote(
                            MetadataFromUrlResponse.Exif.Makernote.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .thumbnail(
                            Thumbnail.builder()
                                .compression(0L)
                                .resolutionUnit(0L)
                                .thumbnailLength(0L)
                                .thumbnailOffset(0L)
                                .xResolution(0L)
                                .yResolution(0L)
                                .build()
                        )
                        .build()
                )
                .format("format")
                .hasColorProfile(true)
                .hasTransparency(true)
                .height(0L)
                .pHash("pHash")
                .quality(0L)
                .size(0L)
                .videoCodec("videoCodec")
                .width(0L)
                .build()

        assertThat(metadataFromUrlResponse.audioCodec()).contains("audioCodec")
        assertThat(metadataFromUrlResponse.bitRate()).contains(0L)
        assertThat(metadataFromUrlResponse.density()).contains(0L)
        assertThat(metadataFromUrlResponse.duration()).contains(0L)
        assertThat(metadataFromUrlResponse.exif())
            .contains(
                MetadataFromUrlResponse.Exif.builder()
                    .exif(
                        ExifDetails.builder()
                            .apertureValue(0.0)
                            .colorSpace(0L)
                            .createDate("CreateDate")
                            .customRendered(0L)
                            .dateTimeOriginal("DateTimeOriginal")
                            .exifImageHeight(0L)
                            .exifImageWidth(0L)
                            .exifVersion("ExifVersion")
                            .exposureCompensation(0.0)
                            .exposureMode(0L)
                            .exposureProgram(0L)
                            .exposureTime(0.0)
                            .flash(0L)
                            .flashpixVersion("FlashpixVersion")
                            .fNumber(0.0)
                            .focalLength(0L)
                            .focalPlaneResolutionUnit(0L)
                            .focalPlaneXResolution(0.0)
                            .focalPlaneYResolution(0.0)
                            .interopOffset(0L)
                            .iso(0L)
                            .meteringMode(0L)
                            .sceneCaptureType(0L)
                            .shutterSpeedValue(0.0)
                            .subSecTime("SubSecTime")
                            .whiteBalance(0L)
                            .build()
                    )
                    .gps(Gps.builder().addGpsVersionId(0L).build())
                    .image(
                        ExifImage.builder()
                            .exifOffset(0L)
                            .gpsInfo(0L)
                            .make("Make")
                            .model("Model")
                            .modifyDate("ModifyDate")
                            .orientation(0L)
                            .resolutionUnit(0L)
                            .software("Software")
                            .xResolution(0L)
                            .yCbCrPositioning(0L)
                            .yResolution(0L)
                            .build()
                    )
                    .interoperability(
                        Interoperability.builder()
                            .interopIndex("InteropIndex")
                            .interopVersion("InteropVersion")
                            .build()
                    )
                    .makernote(
                        MetadataFromUrlResponse.Exif.Makernote.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .thumbnail(
                        Thumbnail.builder()
                            .compression(0L)
                            .resolutionUnit(0L)
                            .thumbnailLength(0L)
                            .thumbnailOffset(0L)
                            .xResolution(0L)
                            .yResolution(0L)
                            .build()
                    )
                    .build()
            )
        assertThat(metadataFromUrlResponse.format()).contains("format")
        assertThat(metadataFromUrlResponse.hasColorProfile()).contains(true)
        assertThat(metadataFromUrlResponse.hasTransparency()).contains(true)
        assertThat(metadataFromUrlResponse.height()).contains(0L)
        assertThat(metadataFromUrlResponse.pHash()).contains("pHash")
        assertThat(metadataFromUrlResponse.quality()).contains(0L)
        assertThat(metadataFromUrlResponse.size()).contains(0L)
        assertThat(metadataFromUrlResponse.videoCodec()).contains("videoCodec")
        assertThat(metadataFromUrlResponse.width()).contains(0L)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val metadataFromUrlResponse =
            MetadataFromUrlResponse.builder()
                .audioCodec("audioCodec")
                .bitRate(0L)
                .density(0L)
                .duration(0L)
                .exif(
                    MetadataFromUrlResponse.Exif.builder()
                        .exif(
                            ExifDetails.builder()
                                .apertureValue(0.0)
                                .colorSpace(0L)
                                .createDate("CreateDate")
                                .customRendered(0L)
                                .dateTimeOriginal("DateTimeOriginal")
                                .exifImageHeight(0L)
                                .exifImageWidth(0L)
                                .exifVersion("ExifVersion")
                                .exposureCompensation(0.0)
                                .exposureMode(0L)
                                .exposureProgram(0L)
                                .exposureTime(0.0)
                                .flash(0L)
                                .flashpixVersion("FlashpixVersion")
                                .fNumber(0.0)
                                .focalLength(0L)
                                .focalPlaneResolutionUnit(0L)
                                .focalPlaneXResolution(0.0)
                                .focalPlaneYResolution(0.0)
                                .interopOffset(0L)
                                .iso(0L)
                                .meteringMode(0L)
                                .sceneCaptureType(0L)
                                .shutterSpeedValue(0.0)
                                .subSecTime("SubSecTime")
                                .whiteBalance(0L)
                                .build()
                        )
                        .gps(Gps.builder().addGpsVersionId(0L).build())
                        .image(
                            ExifImage.builder()
                                .exifOffset(0L)
                                .gpsInfo(0L)
                                .make("Make")
                                .model("Model")
                                .modifyDate("ModifyDate")
                                .orientation(0L)
                                .resolutionUnit(0L)
                                .software("Software")
                                .xResolution(0L)
                                .yCbCrPositioning(0L)
                                .yResolution(0L)
                                .build()
                        )
                        .interoperability(
                            Interoperability.builder()
                                .interopIndex("InteropIndex")
                                .interopVersion("InteropVersion")
                                .build()
                        )
                        .makernote(
                            MetadataFromUrlResponse.Exif.Makernote.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .thumbnail(
                            Thumbnail.builder()
                                .compression(0L)
                                .resolutionUnit(0L)
                                .thumbnailLength(0L)
                                .thumbnailOffset(0L)
                                .xResolution(0L)
                                .yResolution(0L)
                                .build()
                        )
                        .build()
                )
                .format("format")
                .hasColorProfile(true)
                .hasTransparency(true)
                .height(0L)
                .pHash("pHash")
                .quality(0L)
                .size(0L)
                .videoCodec("videoCodec")
                .width(0L)
                .build()

        val roundtrippedMetadataFromUrlResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(metadataFromUrlResponse),
                jacksonTypeRef<MetadataFromUrlResponse>(),
            )

        assertThat(roundtrippedMetadataFromUrlResponse).isEqualTo(metadataFromUrlResponse)
    }
}
