// File generated from our OpenAPI spec by Stainless.

package io.imagekit.io.models.accounts.urlendpoints

import io.imagekit.io.core.JsonValue
import io.imagekit.io.core.Params
import io.imagekit.io.core.checkRequired
import io.imagekit.io.core.http.Headers
import io.imagekit.io.core.http.QueryParams
import java.util.Objects
import java.util.Optional
import kotlin.jvm.optionals.getOrNull

/**
 * **Note:** This API is currently in beta. Updates the URL‑endpoint identified by `id` and returns
 * the updated object.
 */
class UrlEndpointUpdateParams
private constructor(
    private val id: String?,
    private val urlEndpointRequest: UrlEndpointRequest,
    private val additionalHeaders: Headers,
    private val additionalQueryParams: QueryParams,
) : Params {

    /**
     * Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new
     * URL-endpoint. For the default URL-endpoint, this is always `default`.
     */
    fun id(): Optional<String> = Optional.ofNullable(id)

    /** Schema for URL endpoint resource. */
    fun urlEndpointRequest(): UrlEndpointRequest = urlEndpointRequest

    fun _additionalBodyProperties(): Map<String, JsonValue> =
        urlEndpointRequest._additionalProperties()

    /** Additional headers to send with the request. */
    fun _additionalHeaders(): Headers = additionalHeaders

    /** Additional query param to send with the request. */
    fun _additionalQueryParams(): QueryParams = additionalQueryParams

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [UrlEndpointUpdateParams].
         *
         * The following fields are required:
         * ```java
         * .urlEndpointRequest()
         * ```
         */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [UrlEndpointUpdateParams]. */
    class Builder internal constructor() {

        private var id: String? = null
        private var urlEndpointRequest: UrlEndpointRequest? = null
        private var additionalHeaders: Headers.Builder = Headers.builder()
        private var additionalQueryParams: QueryParams.Builder = QueryParams.builder()

        @JvmSynthetic
        internal fun from(urlEndpointUpdateParams: UrlEndpointUpdateParams) = apply {
            id = urlEndpointUpdateParams.id
            urlEndpointRequest = urlEndpointUpdateParams.urlEndpointRequest
            additionalHeaders = urlEndpointUpdateParams.additionalHeaders.toBuilder()
            additionalQueryParams = urlEndpointUpdateParams.additionalQueryParams.toBuilder()
        }

        /**
         * Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a
         * new URL-endpoint. For the default URL-endpoint, this is always `default`.
         */
        fun id(id: String?) = apply { this.id = id }

        /** Alias for calling [Builder.id] with `id.orElse(null)`. */
        fun id(id: Optional<String>) = id(id.getOrNull())

        /** Schema for URL endpoint resource. */
        fun urlEndpointRequest(urlEndpointRequest: UrlEndpointRequest) = apply {
            this.urlEndpointRequest = urlEndpointRequest
        }

        fun additionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun additionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun putAdditionalHeader(name: String, value: String) = apply {
            additionalHeaders.put(name, value)
        }

        fun putAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.put(name, values)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun replaceAdditionalHeaders(name: String, value: String) = apply {
            additionalHeaders.replace(name, value)
        }

        fun replaceAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.replace(name, values)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun removeAdditionalHeaders(name: String) = apply { additionalHeaders.remove(name) }

        fun removeAllAdditionalHeaders(names: Set<String>) = apply {
            additionalHeaders.removeAll(names)
        }

        fun additionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun additionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun putAdditionalQueryParam(key: String, value: String) = apply {
            additionalQueryParams.put(key, value)
        }

        fun putAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.put(key, values)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.putAll(additionalQueryParams)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.putAll(additionalQueryParams)
            }

        fun replaceAdditionalQueryParams(key: String, value: String) = apply {
            additionalQueryParams.replace(key, value)
        }

        fun replaceAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.replace(key, values)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.replaceAll(additionalQueryParams)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.replaceAll(additionalQueryParams)
            }

        fun removeAdditionalQueryParams(key: String) = apply { additionalQueryParams.remove(key) }

        fun removeAllAdditionalQueryParams(keys: Set<String>) = apply {
            additionalQueryParams.removeAll(keys)
        }

        /**
         * Returns an immutable instance of [UrlEndpointUpdateParams].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```java
         * .urlEndpointRequest()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): UrlEndpointUpdateParams =
            UrlEndpointUpdateParams(
                id,
                checkRequired("urlEndpointRequest", urlEndpointRequest),
                additionalHeaders.build(),
                additionalQueryParams.build(),
            )
    }

    fun _body(): UrlEndpointRequest = urlEndpointRequest

    fun _pathParam(index: Int): String =
        when (index) {
            0 -> id ?: ""
            else -> ""
        }

    override fun _headers(): Headers = additionalHeaders

    override fun _queryParams(): QueryParams = additionalQueryParams

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is UrlEndpointUpdateParams &&
            id == other.id &&
            urlEndpointRequest == other.urlEndpointRequest &&
            additionalHeaders == other.additionalHeaders &&
            additionalQueryParams == other.additionalQueryParams
    }

    override fun hashCode(): Int =
        Objects.hash(id, urlEndpointRequest, additionalHeaders, additionalQueryParams)

    override fun toString() =
        "UrlEndpointUpdateParams{id=$id, urlEndpointRequest=$urlEndpointRequest, additionalHeaders=$additionalHeaders, additionalQueryParams=$additionalQueryParams}"
}
